{% set version = "1.7" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-sccs
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/SCCS_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/SCCS/SCCS_{{ version }}.tar.gz
  sha256: 745b9c872c3e8feb1b9f94b1168b7bfb005c0d8be459a4be1573f25b02efa733

build:
  merge_build_host: true  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-r.methodss3
    - r-corpcor
    - r-fda
    - r-gnm
    - r-survival
  run:
    - r-base
    - r-r.methodss3
    - r-corpcor
    - r-fda
    - r-gnm
    - r-survival

test:
  commands:
    - $R -e "library('SCCS')"           # [not win]
    - "\"%R%\" -e \"library('SCCS')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=SCCS
  license: GPL-2.0-or-later
  summary: 'Various self-controlled case series models used to investigate associations between time-varying exposures such as vaccines or other drugs or non drug exposures and an adverse event can be fitted. Detailed information on the self-controlled case series method and its extensions with more examples can be found
    in Farrington, P., Whitaker, H., and Ghebremichael Weldeselassie, Y. (2018, ISBN: 978-1-4987-8159-6. Self-controlled Case Series studies: A modelling Guide with R. Boca Raton: Chapman & Hall/CRC Press) and <https://sccs-studies.info/index.html>.'
  license_family: GPL2
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2'

extra:
  recipe-maintainers:
    - conda-forge/r
    - leej3

# Package: SCCS
# Type: Package
# Title: The Self-Controlled Case Series Method
# Version: 1.6
# Date: 2022-07-04
# Author: Yonas Ghebremichael Weldeselassie, Heather Whitaker, Paddy Farrington
# Maintainer: "Yonas Ghebremichael Weldeselassie" <yonas.weldeselassie@open.ac.uk>
# Description: Various self-controlled case series models used to investigate associations between time-varying exposures such as vaccines or other drugs or non drug exposures and an adverse event can be fitted. Detailed information on the self-controlled case series method and its extensions with more examples can be found in Farrington, P., Whitaker, H., and Ghebremichael Weldeselassie, Y. (2018, ISBN: 978-1-4987-8159-6. Self-controlled Case Series studies: A modelling Guide with R. Boca Raton: Chapman & Hall/CRC Press) and <https://sccs-studies.info/index.html>.
# License: GPL (>= 2)
# Depends: R (>= 2.14.0)
# Imports: survival, splines, corpcor, fda, R.methodsS3, gnm
# LazyData: yes
# Packaged: 2022-07-04 22:50:06 UTC; u1673493
# NeedsCompilation: no
# Repository: CRAN
# Date/Publication: 2022-07-05 14:20:09 UTC
